/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class DataAnggota extends javax.swing.JFrame {

    /**
     * Creates new form DataStokBarang
     */
    public DataAnggota()throws RemoteException, NotBoundException {
        initComponents();
        loadAnggota();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bRubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tNpm = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tTempatLahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tTanggalLahir = new javax.swing.JTextField();
        tProdi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        bHapus.setBackground(new java.awt.Color(255, 102, 102));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bKeluar.setBackground(new java.awt.Color(255, 102, 102));
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bRubah.setBackground(new java.awt.Color(255, 102, 102));
        bRubah.setText("Rubah");
        bRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRubahActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Data Anggota");

        jLabel2.setText("NPM");

        jLabel3.setText("Nama");

        tNama.setBackground(new java.awt.Color(255, 204, 204));
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tNpm.setBackground(new java.awt.Color(255, 204, 204));

        bSimpan.setBackground(new java.awt.Color(255, 102, 102));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NPM", "Nama", "Tempat Lahir", "Tanggal Lahir", "Prodi"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jLabel5.setText("Tempat Lahir");

        tTempatLahir.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setText("Tanggal Lahir");

        tTanggalLahir.setBackground(new java.awt.Color(255, 204, 204));

        tProdi.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setText("Prodi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tNama)
                                        .addComponent(tNpm, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(tTempatLahir))
                                    .addComponent(tTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bRubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bRubah)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tNpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bSimpan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bHapus)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(bKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAnggota() {
        try {
            Connection c = Koneksi.getConnection();
            Statement s = c.createStatement();
            String sql = "SELECT * from dataanggota";
            ResultSet r = s.executeQuery(sql);
            while (r.next())    {
                String npm = r.getString("NPM");
                String nama = r.getString("Nama");
                String tempatLahir = r.getString("TempatLahir");
                String tanggalLahir = r.getString("TanggalLahir");
                String prodi = r.getString("Prodi");
                String tbData[] = {npm,nama,tempatLahir,tanggalLahir,prodi};
                DefaultTableModel tblModel = (DefaultTableModel)tblBarang.getModel();
                tblModel.addRow(tbData);
            }
            r.close(); 
            s.close(); 
        }   catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }
    
    private void refreshTabel() {
        DefaultTableModel model = (DefaultTableModel)
        tblBarang.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        }
    }
    
    private void clear(){ 
        tNpm.setText("");
        tNama.setText("");
        tTempatLahir.setText("");
        tTanggalLahir.setText("");
        tProdi.setText("");
    }
    
    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if (tNpm.getText().equals("") || tNama.getText().equals("") 
                || tTempatLahir.getText().equals("") || tTanggalLahir.getText().equals("")
                || tProdi.getText().equals(""))  {
            JOptionPane.showMessageDialog(null, "Silahkan Input Data Dulu");
        }
        else{
            try {       
                String npm = tNpm.getText();
                String nama = tNama.getText();
                String tempatLahir = tTempatLahir.getText();
                String tanggalLahir = tTanggalLahir.getText();
                String prodi = tProdi.getText();
                
                Connection c = Koneksi.getConnection();
                String sql = "INSERT INTO dataanggota (NPM,Nama,TempatLahir,TanggalLahir"
                        + ",prodi) VALUES (?,?,?,?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, npm);
                p.setString(2, nama);
                p.setString(3, tempatLahir);
                p.setString(4, tanggalLahir);
                p.setString(5, prodi);
                p.executeUpdate();
                p.close();
                refreshTabel();
                loadAnggota();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } 
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();
        TableModel model = tblBarang.getModel();
        tNpm.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),0).toString());
        tNama.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),1).toString());
        tTempatLahir.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),2).toString());
        tTanggalLahir.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),3).toString());
        tProdi.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),4).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void bRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRubahActionPerformed
        // TODO add your handling code here:
        if (tNpm.getText().equals("") || tNama.getText().equals("") 
                || tTempatLahir.getText().equals("") || tTanggalLahir.getText().equals("")
                || tProdi.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di Update");
        }else{
            try {
                String npm = tNpm.getText();
                String nama = tNama.getText();
                String tempatLahir = tTempatLahir.getText();
                String tanggalLahir = tTanggalLahir.getText();
                String prodi = tProdi.getText();
                
                Connection c = Koneksi.getConnection();
                String sql = "update dataanggota set Nama = ?, TempatLahir = ?, TanggalLahir = ?"
                        + ", Prodi = ? where NPM = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, nama);
                p.setString(2, tempatLahir);
                p.setString(3, tanggalLahir);
                p.setString(4, prodi);
                p.setString(5, npm);
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "data berhasil dirubah");
                refreshTabel();
                loadAnggota();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_bRubahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        if (tNpm.getText().equals("") || tNama.getText().equals("") 
                || tTempatLahir.getText().equals("") || tTanggalLahir.getText().equals("")
                || tProdi.getText().equals(""))    {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di Delete");
        }   else    {
            try {
                String npm = tNpm.getText();
                
                Connection c = Koneksi.getConnection(); 
                String sql = "DELETE FROM dataanggota where NPM = ?"; 
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, npm); 
                p.executeUpdate();
                p.close(); 
                JOptionPane.showMessageDialog(this, "data berhasil dihapus");
                refreshTabel();
                loadAnggota();   
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        MenuUtama mu = new MenuUtama();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRubah;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNpm;
    private javax.swing.JTextField tProdi;
    private javax.swing.JTextField tTanggalLahir;
    private javax.swing.JTextField tTempatLahir;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
