/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class DataBuku extends javax.swing.JFrame {

    /**
     * Creates new form DataStokBarang
     */
    public DataBuku()throws RemoteException, NotBoundException {
        initComponents();
        loadBuku();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bHapus = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        bRubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tJudul = new javax.swing.JTextField();
        tKode = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tJenis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tTanggalTerbit = new javax.swing.JTextField();
        tPengarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tStok = new javax.swing.JTextField();
        bDiagram = new javax.swing.JButton();
        bLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        bHapus.setBackground(new java.awt.Color(102, 102, 255));
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bKeluar.setBackground(new java.awt.Color(102, 102, 255));
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        bRubah.setBackground(new java.awt.Color(102, 102, 255));
        bRubah.setText("Rubah");
        bRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRubahActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Data Buku");

        jLabel2.setText("Kode Buku");

        jLabel3.setText("Judul Buku");

        tJudul.setBackground(new java.awt.Color(204, 204, 255));
        tJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tJudulActionPerformed(evt);
            }
        });

        tKode.setBackground(new java.awt.Color(204, 204, 255));

        bSimpan.setBackground(new java.awt.Color(102, 102, 255));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Judul", "Jenis", "Tanggal Terbit", "Pengarang", "Stok"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jLabel5.setText("Jenis");

        tJenis.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setText("Tanggal Terbit");

        tTanggalTerbit.setBackground(new java.awt.Color(204, 204, 255));
        tTanggalTerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTanggalTerbitActionPerformed(evt);
            }
        });

        tPengarang.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setText("Pengarang");

        jLabel8.setText("Stok Buku");

        tStok.setBackground(new java.awt.Color(204, 204, 255));

        bDiagram.setBackground(new java.awt.Color(102, 102, 255));
        bDiagram.setText("Diagram");
        bDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiagramActionPerformed(evt);
            }
        });

        bLaporan.setBackground(new java.awt.Color(102, 102, 255));
        bLaporan.setText("Laporan");
        bLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                    .addGap(37, 37, 37))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tJudul)
                                        .addComponent(tKode, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                        .addComponent(tJenis))
                                    .addComponent(tTanggalTerbit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bRubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bDiagram)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bLaporan)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bRubah)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bSimpan)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bHapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tTanggalTerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(bDiagram))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(bLaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(bKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBuku() {
        try {
            Connection c = Koneksi.getConnection();
            Statement s = c.createStatement();
            String sql = "SELECT * from databuku";
            ResultSet r = s.executeQuery(sql);
            while (r.next())    {
                String kode = r.getString("KodeBuku");
                String judul = r.getString("JudulBuku");
                String jenis = r.getString("Jenis");
                String tglTerbit = r.getString("TglTerbit");
                String pengarang = r.getString("Pengarang");
                String stok = r.getString("StokBuku");
                String tbData[] = {kode,judul,jenis,tglTerbit,pengarang,stok};
                DefaultTableModel tblModel = (DefaultTableModel)tblBarang.getModel();
                tblModel.addRow(tbData);
            }
            r.close(); 
            s.close(); 
        }   catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }
    
    private void refreshTabel() {
        DefaultTableModel model = (DefaultTableModel)
        tblBarang.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        }
    }
    
    private void clear(){ 
        tKode.setText("");
        tJudul.setText("");
        tJenis.setText("");
        tTanggalTerbit.setText("");
        tPengarang.setText("");
        tStok.setText("");
    }
    
    private void tJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tJudulActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().equals("") || tJudul.getText().equals("") 
                || tJenis.getText().equals("") || tTanggalTerbit.getText().equals("")
                || tPengarang.getText().equals("") || tStok.getText().equals(""))  {
            JOptionPane.showMessageDialog(null, "Silahkan Input Data Dulu");
        }
        else{
            try {       
                String kode = tKode.getText();
                String judul = tJudul.getText();
                String jenis = tJenis.getText();
                String tglTerbit = tTanggalTerbit.getText();
                String pengarang = tPengarang.getText();
                String stok = tStok.getText();
                
                Connection c = Koneksi.getConnection();
                String sql = "INSERT INTO databuku (KodeBuku,JudulBuku,Jenis,TglTerbit,Pengarang"
                        + ",StokBuku) VALUES (?,?,?,?,?,?)";
                PreparedStatement p = c.prepareStatement(sql);
                p.setInt(1, Integer.parseInt(kode));
                p.setString(2, judul);
                p.setString(3, jenis);
                p.setString(4, tglTerbit);
                p.setString(5, pengarang);
                p.setString(6, stok);
                p.executeUpdate();
                p.close();
                refreshTabel();
                loadBuku();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            } 
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();
        TableModel model = tblBarang.getModel();
        tKode.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),0).toString());
        tJudul.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),1).toString());
        tJenis.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),2).toString());
        tTanggalTerbit.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),3).toString());
        tPengarang.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),4).toString());
        tStok.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),5).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void bRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRubahActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().equals("") || tJudul.getText().equals("") 
                || tJenis.getText().equals("") || tTanggalTerbit.getText().equals("")
                || tPengarang.getText().equals("") || tStok.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di Update");
        }else{
            try {
                String kode = tKode.getText();
                String judul = tJudul.getText();
                String jenis = tJenis.getText();
                String tglTerbit = tTanggalTerbit.getText();
                String pengarang = tPengarang.getText();
                String stok = tStok.getText();
                
                Connection c = Koneksi.getConnection();
                String sql = "update databuku set JudulBuku = ?, Jenis = ?, TglTerbit = ?"
                        + ", Pengarang = ?, StokBuku = ? where KodeBuku = ?";
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, judul);
                p.setString(2, jenis);
                p.setString(3, tglTerbit);
                p.setString(4, pengarang);
                p.setString(5, stok);
                p.setInt(6, Integer.parseInt(kode));
                p.executeUpdate();
                p.close();
                JOptionPane.showMessageDialog(this, "data berhasil dirubah");
                refreshTabel();
                loadBuku();
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_bRubahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        if (tKode.getText().equals("") || tJudul.getText().equals("") 
                || tJenis.getText().equals("") || tTanggalTerbit.getText().equals("")
                || tPengarang.getText().equals("") || tStok.getText().equals(""))    {
            JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan di Delete");
        }   else    {
            try {
                String kode = tKode.getText();
                
                Connection c = Koneksi.getConnection(); 
                String sql = "DELETE FROM databuku where KodeBuku = ?"; 
                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, kode); 
                p.executeUpdate();
                p.close(); 
                JOptionPane.showMessageDialog(this, "data berhasil dihapus");
                refreshTabel();
                loadBuku();   
                clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        MenuUtama mu = new MenuUtama();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiagramActionPerformed
        // TODO add your handling code here:
        String namatable = "databuku";
        DiagramPie hasil = new DiagramPie();
        try {
            hasil.setNilai(namatable);
        } catch (SQLException ex) {
            Logger.getLogger(DataBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
        hasil.setVisible(true);
    }//GEN-LAST:event_bDiagramActionPerformed

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = 
                    JasperFillManager.fillReport(getClass().getResourceAsStream("dataBuku.jasper"), null, 
            Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bLaporanActionPerformed

    private void tTanggalTerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTanggalTerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTanggalTerbitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDiagram;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bLaporan;
    private javax.swing.JButton bRubah;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tJenis;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tPengarang;
    private javax.swing.JTextField tStok;
    private javax.swing.JTextField tTanggalTerbit;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
