/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form stokbarang
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAnggota1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bBuku = new javax.swing.JButton();
        bAnggota = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bPeminjaman = new javax.swing.JButton();

        bAnggota1.setBackground(new java.awt.Color(255, 204, 255));
        bAnggota1.setText("Anggota");
        bAnggota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnggota1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        bBuku.setBackground(new java.awt.Color(204, 204, 0));
        bBuku.setText("Buku");
        bBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBukuActionPerformed(evt);
            }
        });

        bAnggota.setBackground(new java.awt.Color(204, 204, 0));
        bAnggota.setText("Anggota");
        bAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnggotaActionPerformed(evt);
            }
        });

        jLabel1.setText("Perpustakaan");

        bPeminjaman.setBackground(new java.awt.Color(204, 204, 0));
        bPeminjaman.setText("Peminjaman");
        bPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPeminjamanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bBuku)
                        .addGap(18, 18, 18)
                        .addComponent(bAnggota)))
                .addGap(18, 18, 18)
                .addComponent(bPeminjaman)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuku)
                    .addComponent(bAnggota)
                    .addComponent(bPeminjaman))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBukuActionPerformed
        // TODO add your handling code here:       
        DataBuku buku = null;
        try {
            buku = new DataBuku();
        } catch (RemoteException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        buku.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bBukuActionPerformed

    private void bAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnggotaActionPerformed
        // TODO add your handling code here:
        DataAnggota anggota = null;
        try {
            anggota = new DataAnggota();
        } catch (RemoteException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        anggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAnggotaActionPerformed

    private void bAnggota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnggota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAnggota1ActionPerformed

    private void bPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPeminjamanActionPerformed
        // TODO add your handling code here:
        Peminjaman peminjaman = null;
        try {
            peminjaman = new Peminjaman();
        } catch (RemoteException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(MenuUtama.class.getName()).log(Level.SEVERE, null, ex);
        }
        peminjaman.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bPeminjamanActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnggota;
    private javax.swing.JButton bAnggota1;
    private javax.swing.JButton bBuku;
    private javax.swing.JButton bPeminjaman;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
