/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import java.awt.Color;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class Peminjaman extends javax.swing.JFrame {

    /**
     * Creates new form DataStokBarang
     */
    public Peminjaman()throws RemoteException, NotBoundException {
        initComponents();
        loadPeminjaman();
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tNpm = new javax.swing.JTextField();
        bSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tJudul = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tKodeBuku = new javax.swing.JTextField();
        tProdi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tKodePeminjaman = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tTanggalPeminjaman = new javax.swing.JTextField();
        bLaporan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        bKeluar.setBackground(new java.awt.Color(102, 255, 102));
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Peminjaman");

        jLabel2.setText("NPM");

        jLabel3.setText("Nama");

        tNama.setEditable(false);
        tNama.setBackground(new java.awt.Color(204, 255, 204));
        tNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaActionPerformed(evt);
            }
        });

        tNpm.setBackground(new java.awt.Color(204, 255, 204));
        tNpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNpmActionPerformed(evt);
            }
        });

        bSimpan.setBackground(new java.awt.Color(102, 255, 102));
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Peminjaman", "NPM", "Nama", "Prodi", "Kode Buku", "Judul Buku", "Tanggal Peminjaman"
            }
        ));
        tblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        jLabel5.setText("Judul Buku");

        tJudul.setEditable(false);
        tJudul.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setText("Kode Buku");

        tKodeBuku.setBackground(new java.awt.Color(204, 255, 204));

        tProdi.setEditable(false);
        tProdi.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setText("Prodi");

        jLabel4.setText("Kode Peminjaman");

        tKodePeminjaman.setEditable(false);
        tKodePeminjaman.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setText("Tanggal Peminjaman");

        tTanggalPeminjaman.setBackground(new java.awt.Color(204, 255, 204));

        bLaporan.setBackground(new java.awt.Color(102, 255, 102));
        bLaporan.setText("Laporan");
        bLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tProdi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(tNama)
                                    .addComponent(tNpm)
                                    .addComponent(tKodeBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(tKodePeminjaman))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tTanggalPeminjaman, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tKodePeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLaporan)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(bKeluar))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tTanggalPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaporanActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp =
            JasperFillManager.fillReport(getClass().getResourceAsStream("dataPeminjaman.jasper"), null,
                Koneksi.getConnection());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bLaporanActionPerformed

    private void tblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMouseClicked
        // TODO add your handling code here:
        int index = tblBarang.getSelectedRow();
        TableModel model = tblBarang.getModel();
        tKodePeminjaman.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),0).toString());
        tNpm.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),1).toString());
        tNama.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),2).toString());
        tProdi.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),3).toString());
        tKodeBuku.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),4).toString());
        tJudul.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),5).toString());
        tTanggalPeminjaman.setText(tblBarang.getValueAt(tblBarang.getSelectedRow(),6).toString());
    }//GEN-LAST:event_tblBarangMouseClicked

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        if (tNpm.getText().equals("") || tKodeBuku.getText().equals(""))  {
            JOptionPane.showMessageDialog(null, "Silahkan Input Data Dulu");
        }
        else{
            try {
                String npm = tNpm.getText();
                String nama = tNama.getText();
                String prodi = tProdi.getText();
                String kodeBuku = tKodeBuku.getText();
                String judul = tJudul.getText();
                String tanggalPeminjaman = tTanggalPeminjaman.getText();
                int jumlah;

                Connection c = Koneksi.getConnection();
                Statement s = c.createStatement();
                String sql = "SELECT * FROM databuku where KodeBuku = '" + kodeBuku
                + "'";
                ResultSet r = s.executeQuery(sql);
                while (r.next())    {
                    try {
                        String stok = r.getString("StokBuku");
                        int stokBuku = Integer.parseInt(stok);
                        if (stokBuku == 0)  {
                            JOptionPane.showMessageDialog(null,"buku sedang dipinjam semua");
                        }   else    {
                            try {
                                sql = "SELECT * FROM databuku where KodeBuku = '" + kodeBuku + "'";
                                r = s.executeQuery(sql);

                                while (r.next())  {
                                    jumlah = Integer.parseInt(r.getString(6)) - 1;
                                    judul = r.getString("JudulBuku");
                                    try {
                                        sql = "SELECT * FROM dataanggota where npm ='" + npm + "'";
                                        r = s.executeQuery(sql);
                                        while (r.next())   {
                                            nama = r.getString("nama");
                                            prodi = r.getString("Prodi");
                                            try {
                                                sql = "INSERT INTO peminjaman (npm,nama,prodi,kodeBuku,judulbuku,tanggalPeminjaman) VALUES (?,?,?,?,?,?)";
                                                PreparedStatement p = c.prepareStatement(sql);
                                                p.setString(1, npm);
                                                p.setString(2, nama);
                                                p.setString(3, prodi);
                                                p.setInt(4, Integer.parseInt(kodeBuku));
                                                p.setString(5, judul);
                                                p.setString(6, tanggalPeminjaman);
                                                p.executeUpdate();
                                                p.close();                                                
                                                try {
                                                    sql = "UPDATE databuku SET StokBuku = ? WHERE KodeBuku = ?";
                                                    p = c.prepareStatement(sql);
                                                    p.setInt(1, jumlah);
                                                    p.setInt(2, Integer.parseInt(kodeBuku));
                                                    p.executeUpdate();
                                                    p.close();

                                                    refreshTabel();
                                                    loadPeminjaman();
                                                    clear();
                                                }   catch (Exception e) {
                                                    JOptionPane.showMessageDialog(null, e.getMessage());
                                                }
                                            }   catch (Exception e) {
                                                JOptionPane.showMessageDialog(null, e.getMessage());
                                            }
                                        }
                                    }   catch (Exception e) {
                                        JOptionPane.showMessageDialog(null, e.getMessage());
                                    }
                                }
                            }   catch(Exception e){
                                JOptionPane.showMessageDialog(null, e.getMessage());
                            }
                        }
                    }   catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                }
                r.close();
                s.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        // TODO add your handling code here:
        MenuUtama mu = new MenuUtama();
        mu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void tNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaActionPerformed

    private void tNpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNpmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNpmActionPerformed

    private void loadPeminjaman() {
        try {
            Connection c = Koneksi.getConnection();
            Statement s = c.createStatement();
            String sql = "SELECT * from peminjaman";
            ResultSet r = s.executeQuery(sql);
            while (r.next())    {
                String kodePeminjaman = r.getString("KodePeminjaman");
                String npm = r.getString("NPM");
                String nama = r.getString("Nama");
                String prodi = r.getString("Prodi");
                String kodeBuku = r.getString("KodeBuku");
                String judul = r.getString("JudulBuku");
                String tanggalPeminjaman = r.getString("TanggalPeminjaman");
                String tbData[] = {kodePeminjaman,npm,nama,prodi,kodeBuku,judul,tanggalPeminjaman};
                DefaultTableModel tblModel = (DefaultTableModel)tblBarang.getModel();
                tblModel.addRow(tbData);
            }
            r.close(); 
            s.close(); 
        }   catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!");
        }
    }
    
    private void refreshTabel() {
        DefaultTableModel model = (DefaultTableModel)
        tblBarang.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        }
    }
    
    private void clear(){ 
        tKodePeminjaman.setText("");
        tNpm.setText("");
        tNama.setText("");
        tProdi.setText("");
        tKodeBuku.setText("");
        tJudul.setText("");
        tTanggalPeminjaman.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bLaporan;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tJudul;
    private javax.swing.JTextField tKodeBuku;
    private javax.swing.JTextField tKodePeminjaman;
    private javax.swing.JTextField tNama;
    private javax.swing.JTextField tNpm;
    private javax.swing.JTextField tProdi;
    private javax.swing.JTextField tTanggalPeminjaman;
    private javax.swing.JTable tblBarang;
    // End of variables declaration//GEN-END:variables
}
