/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanjavadatabase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class Karyawan extends javax.swing.JFrame {

    /**
     * Creates new form Karyawan
     */
    public Karyawan() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textNotelp = new javax.swing.JTextField();
        cJabatan = new javax.swing.JComboBox<>();
        jSimpan = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        textNo = new javax.swing.JTextField();
        jBatal = new javax.swing.JButton();
        tbLaporan = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA KARYAWAN");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama Karyawan");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Jabatan");

        jLabel5.setText("Alamat");

        jLabel6.setText("Email");

        jLabel7.setText("No. Telpon");

        cJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IT Engineer", "Network Administrator", "Database Administrator" }));
        cJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJabatanActionPerformed(evt);
            }
        });

        jSimpan.setText("Simpan");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jKeluar.setText("Keluar");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "NIP", "Nama Karyawan", "Jabatan", "Alamat", "Email", "No Telpon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKaryawanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKaryawan);

        textNo.setText("No.");

        jBatal.setText("Batal");
        jBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatalActionPerformed(evt);
            }
        });

        tbLaporan.setText("Laporan");
        tbLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textAlamat)
                                    .addComponent(textEmail)
                                    .addComponent(textNotelp)
                                    .addComponent(textNama)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textNip)
                                        .addGap(18, 18, 18)
                                        .addComponent(textNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbLaporan)
                        .addGap(18, 18, 18)
                        .addComponent(jSimpan)
                        .addGap(27, 27, 27)
                        .addComponent(jEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jHapus)
                        .addGap(18, 18, 18)
                        .addComponent(jBatal)
                        .addGap(18, 18, 18)
                        .addComponent(jKeluar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSimpan)
                    .addComponent(jKeluar)
                    .addComponent(jHapus)
                    .addComponent(jBatal)
                    .addComponent(jEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbLaporan))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        // TODO add your handling code here:
        String nip = textNip.getText();
        String nama = textNama.getText(); 
        String jabatan = (String)cJabatan.getSelectedItem();
        String alamat = textAlamat.getText(); 
        String email = textEmail.getText();
        String notelp = textNotelp.getText();
        
        try{ 
            Connection c = Config.getKoneksi(); 
            String sql = "INSERT INTO KARYAWAN(nip,nama,jabatan,alamat,email,no_telp) VALUES (?, ?, ?, ?, ?,?)"; 
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nip); 
            p.setString(2, nama);
            p.setString(3, jabatan);
            p.setString(4, alamat); 
            p.setString(5, email); 
            p.setString(6, notelp);
            p.executeUpdate();
            p.close(); 
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabel();
        loadData();
    }//GEN-LAST:event_jSimpanActionPerformed

    private void cJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJabatanActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_cJabatanActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        String no = textNo.getText();
        try{
            Connection c = Config.getKoneksi();
            String sql = "delete FROM KARYAWAN where no =?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1,no);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this,"data berhasil dihapus");
            refreshText();
            refreshTabel();
            loadData();
        }
        catch (SQLException ex){
             System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabel();
        loadData();
        refreshText();
    }//GEN-LAST:event_jHapusActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jKeluarActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
        String no = textNo.getText();
        String nip = textNip.getText();
        String nama = textNama.getText(); 
        String jabatan = (String)cJabatan.getSelectedItem();
        String alamat = textAlamat.getText(); 
        String email = textEmail.getText();
        String notelp = textNotelp.getText();
        
        try{ 
            Connection c = Config.getKoneksi(); 
            String sql = "UPDATE KARYAWAN SET nip=?,nama=?,jabatan=?,alamat=?,email=?,no_telp=? where no=?"; 
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nip); 
            p.setString(2, nama);
            p.setString(3, jabatan);
            p.setString(4, alamat); 
            p.setString(5, email); 
            p.setString(6, notelp);
            p.setString(7, no);
            p.executeUpdate();
            p.close(); 
            JOptionPane.showMessageDialog(this, "data berhasil dirubah");
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabel();
        loadData();
        refreshText();
    }//GEN-LAST:event_jEditActionPerformed

    private void tabelKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKaryawanMouseClicked
        // TODO add your handling code here:
        int index = tabelKaryawan.getSelectedRow();
        TableModel model = tabelKaryawan.getModel();
        textNo.setText(model.getValueAt(index, 0).toString());
        textNip.setText(model.getValueAt(index, 1).toString());
        textNama.setText(model.getValueAt(index, 2).toString());
        Object obj = tabelKaryawan.getValueAt(index,3);
        cJabatan.setSelectedItem(obj);
        
        textAlamat.setText(model.getValueAt(index, 4).toString());
        textEmail.setText(model.getValueAt(index, 5).toString());
        textNotelp.setText(model.getValueAt(index, 6).toString());
    }//GEN-LAST:event_tabelKaryawanMouseClicked

    private void jBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatalActionPerformed
        // TODO add your handling code here:
        refreshTabel();
        loadData();
        refreshText();
    }//GEN-LAST:event_jBatalActionPerformed

    private void tbLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLaporanActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("dataKaryawan.jasper"),
                    null, Config.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_tbLaporanActionPerformed

    private void loadData(){
        try{ 
            Connection c = Config.getKoneksi(); 
            Statement s = c.createStatement(); 
        
            String sql = "SELECT * FROM KARYAWAN"; 
            ResultSet r = s.executeQuery(sql); 
        while (r.next()) { 
            // lakukan penelusuran baris 
            String no = r.getString("no");
            String nip = r.getString("nip");
            String nama = r.getString("nama");
            String jabatan = r.getString("jabatan");
            String alamat = r.getString("alamat");
            String email = r.getString("email");
            String notelp = r.getString("no_telp");
            
            String tbData[] = {no,nip,nama,jabatan,alamat,email,notelp};
            
            DefaultTableModel tblModel = (DefaultTableModel)tabelKaryawan.getModel();
            tblModel.addRow(tbData);
            } 
        r.close(); 
        s.close(); 
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        } 
    }

    private void refreshTabel(){
        DefaultTableModel model =(DefaultTableModel) 
        tabelKaryawan.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        } 
    }
    
    private void refreshText(){
        textNip.setText("");
        textNama.setText("");
        textAlamat.setText("");
        textEmail.setText("");
        textNotelp.setText("");
        textNip.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cJabatan;
    private javax.swing.JButton jBatal;
    private javax.swing.JButton jEdit;
    private javax.swing.JButton jHapus;
    private javax.swing.JButton jKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabelKaryawan;
    private javax.swing.JButton tbLaporan;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNip;
    private javax.swing.JTextField textNo;
    private javax.swing.JTextField textNotelp;
    // End of variables declaration//GEN-END:variables
}
