package javagui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class CheckBoxRadioButton extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CheckBoxRadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rBerwarna = new javax.swing.JRadioButton();
        rTransparan = new javax.swing.JRadioButton();
        chkHijau = new javax.swing.JCheckBox();
        chkBiru = new javax.swing.JCheckBox();
        chkMerah = new javax.swing.JCheckBox();
        lblTipeWarna = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtWarna = new javax.swing.JTextArea();
        chkKuning = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(rBerwarna);
        rBerwarna.setText("Berwarna");
        rBerwarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBerwarnaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rTransparan);
        rTransparan.setText("Transparan");
        rTransparan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTransparanActionPerformed(evt);
            }
        });

        chkHijau.setText("Hijau");
        chkHijau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkHijauActionPerformed(evt);
            }
        });

        chkBiru.setText("Biru");
        chkBiru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBiruActionPerformed(evt);
            }
        });

        chkMerah.setText("Merah");
        chkMerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMerahActionPerformed(evt);
            }
        });

        lblTipeWarna.setText("Tipe Warna :");

        txtWarna.setColumns(20);
        txtWarna.setRows(5);
        jScrollPane1.setViewportView(txtWarna);

        chkKuning.setText("Kuning");
        chkKuning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKuningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBerwarna)
                    .addComponent(rTransparan)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBiru)
                            .addComponent(chkHijau)
                            .addComponent(chkMerah)
                            .addComponent(chkKuning))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipeWarna)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rBerwarna)
                    .addComponent(lblTipeWarna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rTransparan)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkHijau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBiru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMerah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkKuning))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBerwarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBerwarnaActionPerformed
        // TODO add your handling code here:
        if(rBerwarna.isSelected())  {
            lblTipeWarna.setText("Tipe warna : " + 
            rBerwarna.getText());
        }
    }//GEN-LAST:event_rBerwarnaActionPerformed

    private void rTransparanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTransparanActionPerformed
        // TODO add your handling code here:
        if(rTransparan.isSelected())  {
            lblTipeWarna.setText("Tipe warna : " + 
            rTransparan.getText());
        }
    }//GEN-LAST:event_rTransparanActionPerformed

    private void chkHijauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkHijauActionPerformed
        // TODO add your handling code here:
        tampilkanWarna();
    }//GEN-LAST:event_chkHijauActionPerformed

    private void chkBiruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBiruActionPerformed
        // TODO add your handling code here:
        tampilkanWarna();
    }//GEN-LAST:event_chkBiruActionPerformed

    private void chkMerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMerahActionPerformed
        // TODO add your handling code here:
        tampilkanWarna();
    }//GEN-LAST:event_chkMerahActionPerformed

    private void chkKuningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKuningActionPerformed
        // TODO add your handling code here:
        tampilkanWarna();
    }//GEN-LAST:event_chkKuningActionPerformed

    private void tampilkanWarna()   {
        StringBuffer warna = new StringBuffer();
        if(chkBiru.isSelected())    {
            warna.append(chkBiru.getText() + " ");
        }
        if(chkHijau.isSelected())    {
            warna.append(chkHijau.getText() + " ");
        }
        if(chkKuning.isSelected())    {
            warna.append(chkKuning.getText() + " ");
        }
        if(chkMerah.isSelected())    {
            warna.append(chkMerah.getText() + " ");
        }
        txtWarna.setText(warna.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckBoxRadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckBoxRadioButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkBiru;
    private javax.swing.JCheckBox chkHijau;
    private javax.swing.JCheckBox chkKuning;
    private javax.swing.JCheckBox chkMerah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipeWarna;
    private javax.swing.JRadioButton rBerwarna;
    private javax.swing.JRadioButton rTransparan;
    private javax.swing.JTextArea txtWarna;
    // End of variables declaration//GEN-END:variables
}
