/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import static java.time.Clock.system;

/**
 *
 * @author atika
 */
public class PesanMakanan extends javax.swing.JFrame {
    private int jumlah, subTotal1, subTotal2, subTotal3, hargaMenu, total, bayar, kembalian;
    private String strTotal = "Harga Total : ";
    private String strKembalian = "Kembalian : ";
    /**
     * Creates new form PesanMakanan
     */
    public PesanMakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cNasiGoreng = new javax.swing.JCheckBox();
        cSateAyam = new javax.swing.JCheckBox();
        cSotoAyam = new javax.swing.JCheckBox();
        jumlahNasi = new javax.swing.JTextField();
        jumlahSate = new javax.swing.JTextField();
        jumlahSoto = new javax.swing.JTextField();
        labelTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumlahBayar = new javax.swing.JTextField();
        labelKembalian = new javax.swing.JLabel();
        tombolBayar = new javax.swing.JButton();
        tombolKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tombolProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pesan Makanan");

        cNasiGoreng.setText("Nasi Goreng (Rp 15.000)");
        cNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNasiGorengActionPerformed(evt);
            }
        });

        cSateAyam.setText("Sate Ayam (Rp 17.000)");
        cSateAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSateAyamActionPerformed(evt);
            }
        });

        cSotoAyam.setText("Soto Ayam (Rp 16.000)");
        cSotoAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSotoAyamActionPerformed(evt);
            }
        });

        jumlahNasi.setText("0");
        jumlahNasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahNasiActionPerformed(evt);
            }
        });

        jumlahSate.setText("0");
        jumlahSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahSateActionPerformed(evt);
            }
        });

        jumlahSoto.setText("0");

        labelTotal.setForeground(new java.awt.Color(255, 0, 0));
        labelTotal.setText("Harga Total : 0");

        jLabel2.setText("Bayar :");

        jumlahBayar.setText("0");
        jumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBayarActionPerformed(evt);
            }
        });

        labelKembalian.setForeground(new java.awt.Color(255, 0, 0));
        labelKembalian.setText("Kembalian : 0");

        tombolBayar.setIcon(new javax.swing.ImageIcon("D:\\CoolYeah\\Semester 6\\Pemrograman Desktop\\Assigntment\\quiz\\duid15.png")); // NOI18N
        tombolBayar.setText("BAYAR");
        tombolBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBayarActionPerformed(evt);
            }
        });

        tombolKeluar.setText("KELUAR");
        tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKeluarActionPerformed(evt);
            }
        });

        jLabel4.setText("MENU PESAN MAKANAN");

        tombolProses.setIcon(new javax.swing.ImageIcon("D:\\CoolYeah\\Semester 6\\Pemrograman Desktop\\Assigntment\\quiz\\chec 15.png")); // NOI18N
        tombolProses.setText("PROSES");
        tombolProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cSateAyam)
                                    .addComponent(cNasiGoreng))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jumlahSate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jumlahNasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cSotoAyam)
                                    .addComponent(tombolBayar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tombolKeluar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jumlahSoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal)
                                    .addComponent(tombolProses))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelKembalian))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNasiGoreng)
                    .addComponent(jumlahNasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSateAyam)
                    .addComponent(jumlahSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cSotoAyam)
                    .addComponent(jumlahSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tombolProses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelKembalian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolBayar)
                    .addComponent(tombolKeluar))
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMakanan(){
        
        if (cNasiGoreng.isSelected()){
            hargaMenu = 15000;
            jumlah = Integer.parseInt(jumlahNasi.getText().trim());
            subTotal1 = hargaMenu * jumlah;
            
        } 
        if (cSateAyam.isSelected()){
            hargaMenu = 17000;
            jumlah = Integer.parseInt(jumlahSate.getText().trim());
            subTotal2 = hargaMenu * jumlah;
        } 
        if (cSotoAyam.isSelected()){
            hargaMenu = 16000;
            jumlah = Integer.parseInt(jumlahSoto.getText().trim());
            subTotal3 = hargaMenu * jumlah;
        }
        
        total = subTotal1 + subTotal2 + subTotal3;
        labelTotal.setText(strTotal + total);
    }
    
    private void cekMakanan(){
        if (cNasiGoreng.isSelected()){
            jumlahNasi.setEnabled(true);
        } else {
            subTotal1=0;
            jumlahNasi.setEnabled(false);
        }
        
        if (cSateAyam.isSelected()){
            jumlahSate.setEnabled(true);
        } else {
            subTotal2=0;
            jumlahSate.setEnabled(false);
        }
        
        if (cSotoAyam.isSelected()){
            jumlahSoto.setEnabled(true);
        } else {
            subTotal3=0;
            jumlahSoto.setEnabled(false);
        }
    }
    private void cSotoAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSotoAyamActionPerformed
        // TODO add your handling code here:
        cekMakanan();
    }//GEN-LAST:event_cSotoAyamActionPerformed

    private void jumlahSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahSateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahSateActionPerformed

    private void cNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNasiGorengActionPerformed
        // TODO add your handling code here:
        cekMakanan();
    }//GEN-LAST:event_cNasiGorengActionPerformed

    private void cSateAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSateAyamActionPerformed
        // TODO add your handling code here:
        cekMakanan();
    }//GEN-LAST:event_cSateAyamActionPerformed

    private void tombolProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolProsesActionPerformed
        // TODO add your handling code here:
        menuMakanan();
    }//GEN-LAST:event_tombolProsesActionPerformed

    private void jumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBayarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlahBayarActionPerformed

    private void tombolBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBayarActionPerformed
        // TODO add your handling code here:
        bayar = Integer.parseInt(jumlahBayar.getText().trim());
        kembalian = bayar - total;
        if (kembalian > 0){
            labelKembalian.setText(strKembalian + kembalian);
        } else if (kembalian < 0){
            labelKembalian.setText("Pembayaran kurang");
        } else if (kembalian == 0){
            labelKembalian.setText("Tidak ada kembalian");
        } else{
            labelKembalian.setText("Masukkan jumlah kembalian");
        }
    }//GEN-LAST:event_tombolBayarActionPerformed

    private void tombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKeluarActionPerformed
        // TODO add your handling code here:
        MenuPopUp gui = new MenuPopUp();
        gui.setVisible(true);
        dispose();
    }//GEN-LAST:event_tombolKeluarActionPerformed

    private void jumlahNasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahNasiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jumlahNasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cNasiGoreng;
    private javax.swing.JCheckBox cSateAyam;
    private javax.swing.JCheckBox cSotoAyam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jumlahBayar;
    private javax.swing.JTextField jumlahNasi;
    private javax.swing.JTextField jumlahSate;
    private javax.swing.JTextField jumlahSoto;
    private javax.swing.JLabel labelKembalian;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JButton tombolBayar;
    private javax.swing.JButton tombolKeluar;
    private javax.swing.JButton tombolProses;
    // End of variables declaration//GEN-END:variables
}
