/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
        loadBarangMasuk();
        loadBarangKeluar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuDiagramPieBarangMasuk = new javax.swing.JMenuItem();
        menuDiagramPieBarangKeluar = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        menuReportBarangMasuk = new javax.swing.JMenuItem();
        menuReportBarangKeluar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTanggalMasuk = new javax.swing.JTextField();
        txtTanggalKeluar = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cKondisi = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        bBarangMasuk = new javax.swing.JButton();
        bHapusMasuk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarangMasuk = new javax.swing.JTable();
        bHapusKeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        bBarangKeluar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBarangKeluar = new javax.swing.JTable();
        bUpdate = new javax.swing.JButton();
        bDiagram = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jCetak = new javax.swing.JButton();

        menuDiagramPieBarangMasuk.setText("Diagram Pie Barang Masuk");
        menuDiagramPieBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiagramPieBarangMasukActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuDiagramPieBarangMasuk);

        menuDiagramPieBarangKeluar.setText("Diagram Pie Barang Keluar");
        menuDiagramPieBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiagramPieBarangKeluarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(menuDiagramPieBarangKeluar);

        menuReportBarangMasuk.setText("Report Barang Masuk");
        menuReportBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportBarangMasukActionPerformed(evt);
            }
        });
        jPopupMenu2.add(menuReportBarangMasuk);

        menuReportBarangKeluar.setText("Report Barang Keluar");
        menuReportBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportBarangKeluarActionPerformed(evt);
            }
        });
        jPopupMenu2.add(menuReportBarangKeluar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PROGRAM INVENTORY BARANG");

        jLabel2.setText("Input Data Barang");

        jLabel3.setText("Kode Barang");

        jLabel4.setText("Nama Barang");

        jLabel5.setText("Tanggal Masuk");

        jLabel6.setText("Tanggal Keluar");

        jLabel7.setText("Jumlah");

        jLabel8.setText("Kondisi");

        txtTanggalKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalKeluarActionPerformed(evt);
            }
        });

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        cKondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak Ringan", "Rusak Berat" }));

        jLabel9.setText("Barang Masuk");

        bBarangMasuk.setText("Barang masuk");
        bBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBarangMasukActionPerformed(evt);
            }
        });

        bHapusMasuk.setText("Hapus");
        bHapusMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusMasukActionPerformed(evt);
            }
        });

        tblBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Tanggal Masuk", "Jumlah", "Kondisi"
            }
        ));
        tblBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarangMasuk);

        bHapusKeluar.setText("Hapus");
        bHapusKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusKeluarActionPerformed(evt);
            }
        });

        jLabel10.setText("Barang Keluar");

        bBarangKeluar.setText("Barang keluar");
        bBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBarangKeluarActionPerformed(evt);
            }
        });

        tblBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Tanggal Masuk", "Tanggal Keluar", "Jumlah", "Kondisi"
            }
        ));
        tblBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBarangKeluar);

        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });

        bDiagram.setText("Diagram");
        bDiagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDiagramMouseClicked(evt);
            }
        });
        bDiagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDiagramActionPerformed(evt);
            }
        });

        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bExit.setText("Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });

        jCetak.setText("Cetak");
        jCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCetakMouseClicked(evt);
            }
        });
        jCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKode)
                            .addComponent(txtNama)
                            .addComponent(txtTanggalMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtTanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDiagram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bClear, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(bExit, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(jCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(bBarangMasuk)
                        .addGap(18, 18, 18)
                        .addComponent(bHapusMasuk)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(bBarangKeluar)
                                .addGap(18, 18, 18)
                                .addComponent(bHapusKeluar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(bBarangMasuk)
                    .addComponent(bHapusMasuk))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTanggalKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(bBarangKeluar)
                    .addComponent(bHapusKeluar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cKondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(bUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bDiagram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCetak))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadBarangMasuk()  {
        try { 
            Connection c = Koneksi.getKoneksi(); 
            Statement s = c.createStatement(); 
            String sql = "SELECT * FROM inventory_barang_masuk"; 
            ResultSet r = s.executeQuery(sql);
            while (r.next()) { 
            // lakukan penelusuran baris 
                String Kd_Barang = r.getString("Kd_Barang");
                String Nama_Barang = r.getString("Nama_Barang");
                String Tanggal_Masuk = r.getString("Tanggal_Masuk");
                String Jumlah = r.getString("Jumlah");
                String Kondisi = r.getString("Kondisi");
                String tbData[] = {Kd_Barang,Nama_Barang,Tanggal_Masuk,Jumlah,Kondisi};
                DefaultTableModel tblModel = (DefaultTableModel)tblBarangMasuk.getModel();
                tblModel.addRow(tbData);
            } 
            r.close(); 
            s.close(); 
        } catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!"); 
        } 
    }
    
    private void loadBarangKeluar() {
        try { 
            Connection c = Koneksi.getKoneksi(); 
            Statement s = c.createStatement(); 
            String sql = "SELECT * FROM inventory_barang_keluar"; 
            ResultSet r = s.executeQuery(sql);
            while (r.next()) { 
            // lakukan penelusuran baris 
                String Kd_Barang = r.getString("Kd_Barang");
                String Nama_Barang = r.getString("Nama_Barang");
                String Tanggal_Masuk = r.getString("Tanggal_Masuk");
                String Tanggal_Keluar = r.getString("Tanggal_Keluar");
                String Jumlah = r.getString("Jumlah");
                String Kondisi = r.getString("Kondisi");
                String tbData[] = {Kd_Barang, Nama_Barang, Tanggal_Masuk, Tanggal_Keluar, Jumlah, Kondisi};
                DefaultTableModel tblModel = (DefaultTableModel) tblBarangKeluar.getModel();
                tblModel.addRow(tbData);
            } 
            r.close(); 
            s.close(); 
        } catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan!"); 
        } 
    }
    
    private void refreshTabelMasuk(){
        DefaultTableModel model = (DefaultTableModel)
        tblBarangMasuk.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        }
    }
    
    private void refreshTabelKeluar(){
        DefaultTableModel model = (DefaultTableModel)
        tblBarangKeluar.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        }
    }
    
    private void refreshText() {
        txtKode.setText("");
        txtNama.setText("");
        txtTanggalKeluar.setText("");
        txtTanggalMasuk.setText("");
        txtJumlah.setText("");
        bBarangMasuk.setEnabled(true);
        bBarangKeluar.setEnabled(true);
        bUpdate.setEnabled(false);
        bHapusKeluar.setEnabled(false);
        bHapusMasuk.setEnabled(false);
    }
    private void txtTanggalKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalKeluarActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void bBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBarangKeluarActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtKode.getText();
        String nama_barang = txtNama.getText();
        String tgl_masuk = txtTanggalMasuk.getText();
        String tgl_keluar = txtTanggalKeluar.getText();
        String jml = txtJumlah.getText();
        String kondisi = cKondisi.getSelectedItem().toString();
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO inventory_barang_keluar(Kd_Barang,Nama_Barang,Tanggal_Masuk,Tanggal_Keluar,Jumlah,Kondisi) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(kd_barang));
            p.setString(2, nama_barang);
            p.setDate(3, Date.valueOf(tgl_masuk));
            p.setDate(4, Date.valueOf(tgl_keluar));
            p.setInt(5, Integer.parseInt(jml));
            p.setString(6, kondisi);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabelKeluar();
        loadBarangKeluar();
        refreshText();
    }//GEN-LAST:event_bBarangKeluarActionPerformed

    private void bBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBarangMasukActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtKode.getText();
        String nama_barang = txtNama.getText();
        String tgl_masuk = txtTanggalMasuk.getText();
        String jml = txtJumlah.getText();
        String kondisi = cKondisi.getSelectedItem().toString();
        
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO inventory_barang_masuk(Kd_Barang,Nama_Barang,"
                    + "Tanggal_Masuk,Jumlah,Kondisi) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(kd_barang));
            p.setString(2, nama_barang);
            p.setDate(3, Date.valueOf(tgl_masuk));
            p.setInt(4, Integer.parseInt(jml));
            p.setString(5, kondisi);
            p.executeUpdate();
            p.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabelMasuk();
        loadBarangMasuk();
        refreshText();
    }//GEN-LAST:event_bBarangMasukActionPerformed

    private void bHapusMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusMasukActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtKode.getText();
        String nama_barang = txtNama.getText();
        
        try{
            Connection c = Koneksi.getKoneksi(); 
            String sql = "DELETE FROM inventory_barang_masuk WHERE  Kd_Barang = ?";  
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(kd_barang));
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            refreshText();
            bBarangMasuk.setEnabled(true);
            bUpdate.setEnabled(false);
            bHapusMasuk.setEnabled(false);
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabelMasuk();
        loadBarangMasuk();
    }//GEN-LAST:event_bHapusMasukActionPerformed

    private void bHapusKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusKeluarActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtKode.getText();
        String nama_barang = txtNama.getText();
        
        try{
            Connection c = Koneksi.getKoneksi(); 
            String sql = "DELETE FROM inventory_barang_keluar WHERE  Kd_Barang = ?";  
            PreparedStatement p = c.prepareStatement(sql);
            p.setInt(1, Integer.parseInt(kd_barang));                p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            refreshText();
            bBarangKeluar.setEnabled(true);
            bUpdate.setEnabled(false);
            bHapusKeluar.setEnabled(false);
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabelKeluar();
        loadBarangKeluar();
    }//GEN-LAST:event_bHapusKeluarActionPerformed

    private void tblBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangMasukMouseClicked
        // TODO add your handling code here:
        int index = tblBarangMasuk.getSelectedRow();
        TableModel model = tblBarangMasuk.getModel();
        txtKode.setText(model.getValueAt(index, 0).toString());
        txtNama.setText(model.getValueAt(index, 1).toString());
        txtTanggalMasuk.setText(model.getValueAt(index, 2).toString());
        txtJumlah.setText(model.getValueAt(index, 3).toString());
        cKondisi.setSelectedItem(model.getValueAt(index, 4));
        bBarangMasuk.setEnabled(false);
        bUpdate.setEnabled(true);
        bHapusMasuk.setEnabled(true);
        txtTanggalKeluar.setText("");
    }//GEN-LAST:event_tblBarangMasukMouseClicked

    private void tblBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangKeluarMouseClicked
        // TODO add your handling code here:
        int index = tblBarangKeluar.getSelectedRow();
        TableModel model = tblBarangKeluar.getModel();
        txtKode.setText(model.getValueAt(index, 0).toString());
        txtNama.setText(model.getValueAt(index, 1).toString());
        txtTanggalMasuk.setText(model.getValueAt(index, 2).toString());
        txtTanggalKeluar.setText(model.getValueAt(index, 3).toString());
        txtJumlah.setText(model.getValueAt(index, 4).toString());
        cKondisi.setSelectedItem(model.getValueAt(index, 5));
        bBarangKeluar.setEnabled(false);
        bUpdate.setEnabled(false);
        bHapusKeluar.setEnabled(true);
    }//GEN-LAST:event_tblBarangKeluarMouseClicked

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        String kd_barang = txtKode.getText();
        String nama_barang = txtNama.getText();
        String tgl_masuk = txtTanggalMasuk.getText();
        String jml = txtJumlah.getText();
        String kondisi = cKondisi.getSelectedItem().toString();
        
        try{ 
            Connection c = Koneksi.getKoneksi(); 
            String sql = "UPDATE inventory_barang_masuk SET Nama_Barang = ?, Tanggal_Masuk = ?, Jumlah = ?, Kondisi = ? where Kd_Barang = ?";  
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama_barang);
            p.setDate(2, java.sql.Date.valueOf(tgl_masuk));
            p.setInt(3, Integer.parseInt(jml));
            p.setString(4, kondisi);
            p.setInt(5, Integer.parseInt(kd_barang));
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(this, "Data berhasil dirubah!");
            bBarangMasuk.setEnabled(true);
            bUpdate.setEnabled(false);
            bHapusMasuk.setEnabled(false);
        } catch(SQLException e) { 
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan"); 
        }
        refreshTabelMasuk();
        loadBarangMasuk();
        refreshText();
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        refreshText();
    }//GEN-LAST:event_bClearActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bExitActionPerformed

    private void bDiagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDiagramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDiagramActionPerformed

    private void menuDiagramPieBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiagramPieBarangMasukActionPerformed
        // TODO add your handling code here:
        String namatable = "inventory_barang_masuk";
        DiagramPie hasil = new DiagramPie();
        hasil.setNilai(namatable);
        hasil.setVisible(true);
    }//GEN-LAST:event_menuDiagramPieBarangMasukActionPerformed

    private void bDiagramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDiagramMouseClicked
        // TODO add your handling code here:
        showpopupMenuDiagram(evt);
    }//GEN-LAST:event_bDiagramMouseClicked

    private void menuDiagramPieBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiagramPieBarangKeluarActionPerformed
        // TODO add your handling code here:
        String namatable = "inventory_barang_keluar";
        DiagramPie hasil = new DiagramPie();
        hasil.setNilai(namatable);
        hasil.setVisible(true);
    }//GEN-LAST:event_menuDiagramPieBarangKeluarActionPerformed

    private void jCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCetakActionPerformed

    private void jCetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCetakMouseClicked
        // TODO add your handling code here:
        showpopupMenuLaporan(evt);
    }//GEN-LAST:event_jCetakMouseClicked

    private void menuReportBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportBarangMasukActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("BarangMasuk.jasper"), null, Koneksi.getKoneksi());
            JasperViewer.viewReport(jp, true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_menuReportBarangMasukActionPerformed

    private void menuReportBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportBarangKeluarActionPerformed
        // TODO add your handling code here:
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("BarangKeluar.jasper"), null, Koneksi.getKoneksi());
            JasperViewer.viewReport(jp, true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_menuReportBarangKeluarActionPerformed

    private void showpopupMenuDiagram(MouseEvent e) {
        jPopupMenu1.show(this, e.getX(), e.getY());
    }
   
    private void showpopupMenuLaporan(MouseEvent e) {
        jPopupMenu2.show(this, e.getX(), e.getY());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBarangKeluar;
    private javax.swing.JButton bBarangMasuk;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDiagram;
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHapusKeluar;
    private javax.swing.JButton bHapusMasuk;
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cKondisi;
    private javax.swing.JButton jCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuDiagramPieBarangKeluar;
    private javax.swing.JMenuItem menuDiagramPieBarangMasuk;
    private javax.swing.JMenuItem menuReportBarangKeluar;
    private javax.swing.JMenuItem menuReportBarangMasuk;
    private javax.swing.JTable tblBarangKeluar;
    private javax.swing.JTable tblBarangMasuk;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggalKeluar;
    private javax.swing.JTextField txtTanggalMasuk;
    // End of variables declaration//GEN-END:variables
}
