/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programakademik;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Alya Aiman Salsabila Arif
 */
public class InputData extends javax.swing.JFrame {

    /**
     * Creates new form InputData
     */
    public InputData() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textkode = new javax.swing.JTextField();
        textNama = new javax.swing.JTextField();
        textJurusan = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAlamat = new javax.swing.JTextArea();
        jSimpan = new javax.swing.JButton();
        jRubah = new javax.swing.JButton();
        jHapus = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        jReset = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id :");

        jLabel2.setText("Nama :");

        jLabel3.setText("Jurusan :");

        jLabel4.setText("Email :");

        jLabel5.setText("Alamat :");

        textkode.setEnabled(false);
        textkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textkodeActionPerformed(evt);
            }
        });

        textAlamat.setColumns(20);
        textAlamat.setRows(5);
        jScrollPane1.setViewportView(textAlamat);

        jSimpan.setText("Simpan");
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jRubah.setText("Rubah");
        jRubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRubahActionPerformed(evt);
            }
        });

        jHapus.setText("Hapus");
        jHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHapusActionPerformed(evt);
            }
        });

        jKeluar.setText("Keluar");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nama", "jurusan", "email", "alamat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelMahasiswa);

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textJurusan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textkode)
                                .addGap(18, 18, 18)
                                .addComponent(jReset))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(jRubah)
                        .addGap(18, 18, 18)
                        .addComponent(jHapus)
                        .addGap(18, 18, 18)
                        .addComponent(jKeluar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReset))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSimpan)
                    .addComponent(jRubah)
                    .addComponent(jHapus)
                    .addComponent(jKeluar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        // TODO add your handling code here:
        String nama = textNama.getText(); 
        String jurusan = textJurusan.getText(); 
        String email = textEmail.getText(); 
        String alamat = textAlamat.getText(); 

        try{ 
            Connection c = Koneksi.getKoneksi(); 
            String sql = "INSERT INTO MAHASISWA(nama,jurusan,email,alamat) VALUES (?, ?, ?, ?)"; 
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama); 
            p.setString(2, jurusan); 
            p.setString(3, email); 
            p.setString(4, alamat); 
            p.executeUpdate();
            p.close(); 
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabel();
        loadData();
    }//GEN-LAST:event_jSimpanActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        // TODO add your handling code here:
        int index = tabelMahasiswa.getSelectedRow();
        TableModel model = tabelMahasiswa.getModel();
        
        textkode.setText(model.getValueAt(index, 0).toString());
        textNama.setText(model.getValueAt(index, 1).toString());
        textJurusan.setText(model.getValueAt(index, 2).toString());
        textEmail.setText(model.getValueAt(index, 3).toString());
        textAlamat.setText(model.getValueAt(index, 4).toString());
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void jRubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRubahActionPerformed
        // TODO add your handling code here:
        String nama = textNama.getText(); 
        String jurusan = textJurusan.getText(); 
        String email = textEmail.getText(); 
        String alamat = textAlamat.getText(); 
        String id = textkode.getText(); 
        
        try{ 
            Connection c = Koneksi.getKoneksi(); 
            String sql = "update mahasiswa set nama = ?,jurusan = ?,email = ?,alamat = ? where id = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, nama); 
            p.setString(2, jurusan); 
            p.setString(3, email); 
            p.setString(4, alamat); 
            p.setString(5, id); 
            p.executeUpdate();
            p.close(); 
            JOptionPane.showMessageDialog(this, "data berhasil dirubah");
            jRubah.setEnabled(false);
            jHapus.setEnabled(false);
            jSimpan.setEnabled(true);
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }   
        refreshTabel();
        loadData();
    }//GEN-LAST:event_jRubahActionPerformed

    private void textkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textkodeActionPerformed

    private void jHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHapusActionPerformed
        // TODO add your handling code here:
        String id = textkode.getText(); 

        try{ 
            Connection c = Koneksi.getKoneksi(); 
            String sql = "DELETE FROM MAHASISWA where id = ?"; 
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id); 
            p.executeUpdate();
            p.close(); 
            JOptionPane.showMessageDialog(this, "data berhasil dihapus");
            jRubah.setEnabled(false);
            jHapus.setEnabled(false);
            jSimpan.setEnabled(true);
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        }
        refreshTabel();
        loadData();
        refreshText();
    }//GEN-LAST:event_jHapusActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        refreshTabel();
        loadData();
        refreshText();
        jSimpan.setEnabled(true);
        jRubah.setEnabled(false);
        jHapus.setEnabled(false);
    }//GEN-LAST:event_jResetActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jKeluarActionPerformed

    private void loadData(){
        try{ 
            Connection c = Koneksi.getKoneksi(); 
            Statement s = c.createStatement(); 
        
            String sql = "SELECT * FROM MAHASISWA"; 
            ResultSet r = s.executeQuery(sql); 
        while (r.next()) { 
            // lakukan penelusuran baris 
            String id = r.getString("id");
            String nama = r.getString("nama");
            String jurusan = r.getString("jurusan");
            String email = r.getString("email");
            String alamat = r.getString("alamat");
            String tbData[] = {id,nama,jurusan,email,alamat};
            DefaultTableModel tblModel = (DefaultTableModel)tabelMahasiswa.getModel();
            tblModel.addRow(tbData);
            } 
        r.close(); 
        s.close(); 
        } catch(SQLException e) { 
            System.out.println("Terjadi Kesalahan"); 
        } 
    }

    private void refreshTabel(){
        DefaultTableModel model =(DefaultTableModel) 
        tabelMahasiswa.getModel();
        while(model.getRowCount()>0){
            model.setRowCount(0);
        } 
    }
    
    private void refreshText(){
        textkode.setText("");
        textNama.setText("");
        textJurusan.setText("");
        textEmail.setText("");
        textAlamat.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jHapus;
    private javax.swing.JButton jKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jReset;
    private javax.swing.JButton jRubah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JTextArea textAlamat;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textJurusan;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textkode;
    // End of variables declaration//GEN-END:variables
}
